# Generated by Django 5.2.6 on 2025-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bodypartimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypartimage',
            name='image',
            field=models.ImageField(upload_to='body_part_images/'),
        ),
    ]
