# Generated by Django 5.2.6 on 2025-10-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('joined', models.IntegerField(default=0)),
                ('max_participants', models.IntegerField(default=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('recurring', models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to='accounts.admin')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('auto_entry', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='accounts.contest')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Contest Participant',
                'verbose_name_plural': 'Contest Participants',
                'ordering': ['-joined_at'],
                'unique_together': {('contest', 'contributor')},
            },
        ),
    ]
