# Generated by Django 5.2.6 on 2025-10-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contest_contestparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
