# Generated by Django 5.2.6 on 2025-10-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_contest_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="card_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
