# Generated by Django 5.2.6 on 2025-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_profile_card_number_profile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmokeSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=200)),
                (
                    "channel",
                    models.CharField(
                        choices=[("Email", "Email"), ("SMS", "SMS")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Smoke Signal",
                "verbose_name_plural": "Smoke Signals",
                "ordering": ["-timestamp"],
            },
        ),
    ]
