# Generated by Django 5.2.6 on 2025-10-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_smokesignal"),
    ]

    operations = [
        migrations.AddField(
            model_name="smokesignal",
            name="recipient",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
