# Generated by Django 5.2.6 on 2025-10-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_favoriteimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="body_part_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contest_submissions",
                to="accounts.bodypartimage",
            ),
        ),
    ]
