# Generated by Django 5.2.6 on 2025-10-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_notification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vote",
            name="consecutive_wins",
            field=models.IntegerField(default=0),
        ),
    ]
