# Generated by Django 5.2.6 on 2025-11-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_vote_unique_together_vote_consecutive_wins"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active_profile_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_active_for",
                to="accounts.bodypartimage",
            ),
        ),
    ]
