# Generated by Django 5.2.6 on 2025-11-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_active_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_recurring_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='next_generation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='parent_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='accounts.contest'),
        ),
    ]
