# Generated by Django 5.2.6 on 2025-12-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_favoritegallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="loser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lost_votes",
                to="accounts.contestparticipant",
            ),
        ),
    ]
