# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_vote_loser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="w9_unique_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="w9_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="w9_completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="w9_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

