# Generated by Django 5.2.6 on 2026-02-17 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_add_yoti_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="yoti_session_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="yoti_verification_data",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="yoti_verification_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="yoti_verified",
        ),
        migrations.CreateModel(
            name="AgeVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=500)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_over_18", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Age Verification",
                "verbose_name_plural": "Age Verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_ag_user_id_25c987_idx",
                    ),
                    models.Index(
                        fields=["is_verified"], name="accounts_ag_is_veri_4c31f7_idx"
                    ),
                ],
            },
        ),
    ]
