"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.6.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-tig6g^5j#vo*+9q^)_d6_!u$-j&e*&fxm--j-@cj3*e8@3ek0^"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "storages",
    # Local apps
    "accounts",
    "dashboard",
    "drf_yasg",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "backend.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "backend.wsgi.application"
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
# Static & Media files
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default: use local media in development, Wasabi in production if configured
USE_WASABI_STORAGE = os.environ.get("USE_WASABI_STORAGE", "true").lower() == "true"

if USE_WASABI_STORAGE:
    # Wasabi (S3-compatible) settings
    WASABI_ACCESS_KEY_ID = os.environ.get("WASABI_ACCESS_KEY_ID")
    WASABI_SECRET_ACCESS_KEY = os.environ.get("WASABI_SECRET_ACCESS_KEY")
    WASABI_BUCKET_NAME = os.environ.get("WASABI_BUCKET_NAME", "se-media")
    WASABI_REGION = os.environ.get("WASABI_REGION", "eu-central-1")
    WASABI_ENDPOINT_URL = os.environ.get(
        "WASABI_ENDPOINT_URL",
        "https://s3.eu-central-1.wasabisys.com",
    )

    AWS_ACCESS_KEY_ID = WASABI_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = WASABI_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = WASABI_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = WASABI_ENDPOINT_URL
    AWS_S3_REGION_NAME = WASABI_REGION

    # S3/Wasabi behavior
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "virtual"  # or "path" if you prefer
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    # Media URLs served directly from Wasabi
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
    MEDIA_ROOT = ""
else:
    # Fallback to local media (e.g. for local dev)
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# DRF / JWT / Schema
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}
SPECTACULAR_SETTINGS = {
    "TITLE": "SE Backend API",
    "DESCRIPTION": "Swagger Schema for Select Exposure",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    # Add JWT Bearer token authentication to Swagger UI
    "SECURITY": [
        {
            "Bearer": []
        }
    ],
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
        }
    },
}
# CORS Configuration - Allow React Frontend
# For production with HTTPS frontend (Vercel) calling HTTP backend, we need to allow all origins
# This is necessary because browsers block mixed content (HTTPS -> HTTP)
# In a proper production setup, the backend should also use HTTPS
CORS_ALLOW_ALL_ORIGINS = True  # Enabled for Vercel HTTPS -> HTTP backend compatibility
CORS_ALLOW_CREDENTIALS = True

# Alternative: If you prefer to whitelist specific origins only, use this instead:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://localhost:3001",
#     "http://127.0.0.1:3000",
#     "http://127.0.0.1:3001",
#     "http://108.61.229.67:3000",
#     "https://se-gamma-olive.vercel.app",
#     "https://se-admin-panel.vercel.app",
# ]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "hannanmalik0321@gmail.com"
EMAIL_HOST_PASSWORD = "ptmtokcfhztuwcwg"

# Twilio SMS Configuration
# IMPORTANT: Set these as environment variables. Never commit secrets to git.
# Required environment variables:
#   - TWILIO_ACCOUNT_SID
#   - TWILIO_AUTH_TOKEN
#   - TWILIO_PHONE_NUMBER (optional, can be provided per request)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')  # Your Twilio phone number (e.g., +1234567890)

# Yoti Age Verification Configuration
# IMPORTANT: Set these as environment variables. Never commit secrets to git.
# Required environment variables:
#   - YOTI_SDK_ID: Your Yoti SDK ID (UUID)
#   - YOTI_API_KEY: Your Yoti API Key (Bearer token)
#   - YOTI_CALLBACK_URL: HTTPS callback URL (required by Yoti, must be HTTPS)
#     For development, use ngrok or similar: https://your-ngrok-url.ngrok.io/api/accounts/verify-age/callback/
#     For production, use your actual HTTPS callback URL
# 
# Note: Uses Bearer token authentication (OAuth 2.0 style)
# The API key should be sent as: Authorization: Bearer {API_KEY}
# The SDK ID should be sent as: Yoti-SDK-Id: {SDK_ID}
YOTI_SDK_ID = os.environ.get('YOTI_SDK_ID', 'd166a758-7100-4626-8f6f-08617879079a')
YOTI_API_KEY = os.environ.get('YOTI_API_KEY', 'L8GLhGceggptE7W7X-mTqvqOJG9GaYq9w6Q4CjP8nob22bWyRpESm0t3NRA=')
# Default to a placeholder - MUST be set to a valid HTTPS URL in production
YOTI_CALLBACK_URL = os.environ.get('YOTI_CALLBACK_URL', 'https://example.com/yoti-callback')