# Generated by Django 5.2.6 on 2025-09-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_age_profile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allow_name_in_search",
            field=models.BooleanField(default=True),
        ),
    ]
