# Generated by Django 5.2.6 on 2025-09-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="id_documents/"),
        ),
    ]
